# Generated by Django 4.1.3 on 2023-02-11 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(verbose_name='date published')),
                ('model_run_time', models.DurationField()),
                ('shade', models.CharField(choices=[('fair', 'Fair'), ('light', 'Light'), ('medium', 'Medium'), ('olive', 'Olive'), ('dark', 'Dark'), ('brown', 'Brown'), ('black', 'Black')], max_length=10)),
                ('age', models.PositiveIntegerField(default=30)),
                ('request_text', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_text', models.CharField(max_length=1000)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.request')),
            ],
        ),
    ]
