# Generated by Django 4.1.6 on 2023-02-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='output_text',
            field=models.CharField(max_length=2000),
        ),
    ]
